name: Nightly build

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TARGET: [release] # refers to a cargo profile
    steps:
    - uses: actions/checkout@v4
    - name: Build in ${{ matrix.BUILD_TARGET }} mode
      run: cargo build --verbose --profile ${{ matrix.BUILD_TARGET }}
    - name: Run tests in "${{ matrix.BUILD_TARGET }}" mode
      run: cargo test --profile ${{ matrix.BUILD_TARGET }}
    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: flora
        path: target/${{ matrix.BUILD_TARGET }}/flora
